### PR TITLE
#4 support for finding batchmates of any year

### PR DESCRIPTION
**Pull request by nkkumawat**

### CODE REVIEW

**Comment by devender-yadav** [comment]
@nkkumawat Thanks for adding new PR While adding "git commit", mention issue id in the message.

For example,  `git commit -m "#4, support for finding batchmates of any year" <some files>`
It will link your commit with that issue.

**Comment by devender-yadav** [comment]
fix for #4

**Comment by devender-yadav** [comment]
Also, check tasks in the description of the issues. Are you familiar with mocha, chai or jasmine test frameworks? Its good practice to have unit tests.

**Comment by nkkumawat** [comment]
Sure sir, I will add unit test cases.

**Pull request closed without merging**
